### ISSUE TITLE
Is soloader 0.5.0 incompatible with litho?

### ISSUE THREAD

**Issue by yschimke** [facebook/Sonar#165]
litho 0.17.0
sonar 0.6.12
soloader 0.5.0
yoga 1.8.0

    java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/com.squareup.okhttptestapp-2/base.apk:classes3.dex)
        at com.facebook.yoga.YogaConfig.<clinit>(YogaConfig.java:19)
        at com.facebook.litho.ComponentsPools.acquireYogaNode(ComponentsPools.java:180)
        at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:206)
        at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:310)
        at com.facebook.litho.Column.resolve(Column.java:88)
        at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:353)
        at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:326)
        at com.facebook.litho.LayoutState.createTree(LayoutState.java:1608)
        at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1795)
        at com.facebook.litho.LayoutState.calculate(LayoutState.java:1224)
        at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1938)
        at com.facebook.litho.ComponentTree.measure(ComponentTree.java:855)
        at com.facebook.litho.LithoView.performLayout(LithoView.java:362)
        at com.facebook.litho.ComponentHost.onLayout(ComponentHost.java:799)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)

**Comment by yschimke** [comment]
Fixed in litho 0.18.0
