### ISSUE TITLE
Pod installed failed when Run the sample code on iOS or on my own project.

### ISSUE THREAD

**Issue by urmyfaith** [facebook/Sonar#30]
Pod installed failed when Run the sample code on iOS or on my own project.

RT.

```
➜  Sample pod install
Analyzing dependencies
[!] A dependency with an external source may not specify version requirements (Yoga).
```

Build On macOS 10.13.3 (17D102), 

```
➜  Sample swift --version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.4.0 
```

**Comment by priteshrnandgaonkar** [comment]
@urmyfaith Running `pod install` from `iOS/Sample` works for me. Can you try upgrading your cocoapod? 

<img width="1680" alt="screen shot 2018-06-12 at 11 37 03 am" src="https://user-images.githubusercontent.com/3865908/41285729-0ed15b82-6e35-11e8-9330-39196fdf5da2.png">

**Comment by urmyfaith** [comment]
I have upgraded cocoapods.

![](https://ws2.sinaimg.cn/large/006tKfTcly1fs8l8mran9j31a60eswre.jpg)

```bash
➜  Sample pod --version
1.5.3
➜  Sample pod install
Analyzing dependencies
Pre-downloading: `ComponentKit` from `https://github.com/facebook/ComponentKit.git`, commit `73acd7995610ad6b009a9a74b8290a54dab7c716`
Fetching podspec for `DoubleConversion` from `../third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../third-party-podspecs/Folly.podspec`
Pre-downloading: `PeerTalk` from `https://github.com/rsms/PeerTalk.git`, commit `588303b43efa5082d654b6f75d1b84a6ba4b5b9e`
Pre-downloading: `RSocket` from `https://github.com/rsocket/rsocket-cpp.git`, commit `11491fb22aaaf29b2702a1723561db51b314dd0f`
[!] Unable to find a specification for 'RSocket'.
➜  Sample pod install
Analyzing dependencies
Pre-downloading: `ComponentKit` from `https://github.com/facebook/ComponentKit.git`, commit `73acd7995610ad6b009a9a74b8290a54dab7c716`
Fetching podspec for `DoubleConversion` from `../third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../third-party-podspecs/Folly.podspec`
Pre-downloading: `PeerTalk` from `https://github.com/rsms/PeerTalk.git`, commit `588303b43efa5082d654b6f75d1b84a6ba4b5b9e`
Pre-downloading: `RSocket` from `https://github.com/rsocket/rsocket-cpp.git`, commit `11491fb22aaaf29b2702a1723561db51b314dd0f`
[!] Unable to find a specification for 'RSocket'.
```

**Comment by padupuy** [comment]
@urmyfaith The docs are not reflecting the repo requirements

Here is better version which comes from [the repo examples](https://github.com/facebook/Sonar/blob/master/iOS/Sample/Podfile)
```
  pod 'EasyWSClient', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/EasyWSClient.podspec'
  pod 'PeerTalk', :git => 'https://github.com/rsms/peertalk'
  pod 'ComponentKit', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/ComponentKit.podspec'
  pod 'Sonar', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/xplat/Sonar/SonarKitCPP.podspec'
  pod 'SonarKit', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec'
  pod 'SonarKit/SonarKitLayoutComponentKitSupport', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec'
  pod 'SonarKit/SKIOSNetworkPlugin', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec'

  pod 'DoubleConversion', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => 'https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/Folly.podspec'
  pod 'Yoga','~>1.8.1', :modular_headers => true
```

@priteshrnandgaonkar Could you please update the docs ?

**Comment by padupuy** [comment]
Still failed during pod install 

Here is my logs 

```
pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-ghdapp`: (``)

Finding Podfile changes
  A ComponentKit
  A EasyWSClient
  A PeerTalk
  A Sonar
  A SonarKit
  A Yoga
  R yoga
  M DoubleConversion
  M Folly
  M glog
  - Firebase
  - Interactable
  - React
  - react-native-maps

Fetching external sources
-> Fetching podspec for `ComponentKit` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/ComponentKit.podspec`
-> Fetching podspec for `DoubleConversion` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/DoubleConversion.podspec`
-> Fetching podspec for `EasyWSClient` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/EasyWSClient.podspec`
-> Fetching podspec for `Folly` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/Folly.podspec`
-> Fetching podspec for `Interactable` from `../node_modules/react-native-interactable`
-> Pre-downloading: `PeerTalk` from `https://github.com/rsms/peertalk`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/rsms/peertalk /var/folders/z0/ncp72vmj72q_4pmjhzm59kdr0000gn/T/d20180612-56675-qh1jxk --template= --single-branch --depth 1
     Cloning into '/var/folders/z0/ncp72vmj72q_4pmjhzm59kdr0000gn/T/d20180612-56675-qh1jxk'...
  $ /usr/bin/git -C /var/folders/z0/ncp72vmj72q_4pmjhzm59kdr0000gn/T/d20180612-56675-qh1jxk rev-parse HEAD
  588303b43efa5082d654b6f75d1b84a6ba4b5b9e
  > Copying PeerTalk from `/Users/padupuy/Library/Caches/CocoaPods/Pods/External/PeerTalk/3cc1488ccfac5531686d44caef0ffbfe` to `Pods/PeerTalk`
-> Fetching podspec for `React` from `../node_modules/react-native`
-> Fetching podspec for `Sonar` from `https://raw.githubusercontent.com/facebook/Sonar/master/xplat/Sonar/SonarKitCPP.podspec`
-> Fetching podspec for `SonarKit` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/SonarKit.podspec`
-> Fetching podspec for `glog` from `https://raw.githubusercontent.com/facebook/Sonar/master/iOS/third-party-podspecs/glog.podspec`
[!] Failed to load 'glog' podspec:
[!] Invalid `glog.podspec` file: No such file or directory @ rb_sysopen - ../scripts/ios-configure-glog.sh.

 #  from /Users/padupuy/adfab/ghd/ws/ghdapp/ios/glog.podspec:8
 #  -------------------------------------------
 #    spec.authors = 'Google'
 >    spec.prepare_command = File.read("../scripts/ios-configure-glog.sh")
 #    spec.source = { :git => 'https://github.com/google/glog.git',
 #  -------------------------------------------


/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:170:in `rescue in store_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/abstract_external_source.rb:156:in `store_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/podspec_source.rb:19:in `block (2 levels) in fetch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:155:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by urmyfaith** [comment]
Instead of download the zip of this repo, I cloned to my mac ,the sample code works using commit 

https://github.com/facebook/Sonar/commit/4fbe638adf39f413e8fb5a20e4de6833a8bbbdd2

Many thanks. @priteshrnandgaonkar @padupuy 


![](https://ws2.sinaimg.cn/large/006tKfTcgy1fs8nokapzoj31420p67n0.jpg)

**Comment by priteshrnandgaonkar** [comment]
This [commit](https://github.com/facebook/Sonar/blob/master/iOS/Sample/Podfile) is the culprit. Fix for this is comming

**Comment by priteshrnandgaonkar** [comment]
@urmyfaith Is this error encountered while running `pod install`

**Comment by urmyfaith** [comment]
@priteshrnandgaonkar no, accured when building for my iPhone.

**Comment by priteshrnandgaonkar** [comment]
Currently we support just simulators for iOS platform. Support for iOS devices will come soon.

**Comment by urmyfaith** [comment]
@priteshrnandgaonkar thanks,Maybe  I seems didn’t noticed that in the readme.

**Comment by priteshrnandgaonkar** [comment]
@urmyfaith We will update it in the documentation. Closing the issue for now.
