### ISSUE TITLE
Sonar keep crash on startup

### ISSUE THREAD

**Issue by vincent-paing** [facebook/Sonar#36]
I followed the getting started guide, and set up in my application as follows:

 ```
if (BuildConfig.DEBUG && SonarUtils.shouldEnableSonar(this)) {
      val client = AndroidSonarClient.getInstance(this)
      client.start()
}
```

Now whenever my app starts, it crashes with following exception
```
FATAL EXCEPTION: SonarEventBaseThread
    Process: com.anitime.schedule, PID: 13943
    java.lang.ExceptionInInitializerError
        at com.facebook.sonar.android.SonarThread.run(SonarThread.java:25)
     Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
        at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:746)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:476)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.sonar.android.SonarThread.run(SonarThread.java:25) 
```

I'm on Android SDK of 28, and on Android Studio of 3.2, and testing on Phone with OS version of 8.0.0

**Comment by hibob224** [comment]
To get around this you can call `SoLoader.init(context, false)` before `AndroidSonarClient.getInstance(this)`. I've opened an issue for this asking if it should be added to the documentation #27

**Comment by jknoxville** [comment]
Thanks for raising this guys, I'll update the docs to reflect it. Closing this one in favor of the first one, #27
