### ISSUE TITLE
Error while building gradle #android

### ISSUE THREAD

**Issue by chainchelliah** [facebook/Sonar#45]
Error: Program type already present: android.arch.lifecycle.LifecycleRegistry$ObserverWithState

	at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
	at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
	at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:121)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:122)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:40)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:110)
	at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)

No use of below one,

debugImplementation ('com.facebook.sonar:sonar:0.0.1'){
        exclude group: 'android'
        exclude group: 'javax'
        exclude group: 'jsr-305'
        exclude group: 'okhttp3'
        exclude group: 'okio'
        exclude group: 'org'
        exclude group: 'com.google'
    }

Looking forward ....

**Comment by priteshrnandgaonkar** [comment]
You can follow #41 . It looks similar. Feel free to reopen if its not same issue.
